In [2]:
#Se importan las librerias necesarias
from random import randint
from random import uniform
import numpy as np
import math

In [3]:
#Se genera la poblacion inicial
matriz = []

for r in range(15):
    fila = []

    for c in range(15):
        fila.append(randint(0, 1))
    
    matriz.append(fila)

matriz = np.array(matriz)

print (matriz)

[[1 0 0 0 0 0 1 1 0 0 1 0 1 0 0]
 [0 0 1 0 0 1 0 1 1 1 0 0 1 0 1]
 [1 1 1 1 1 1 1 1 0 1 1 0 1 0 1]
 [0 0 0 0 1 0 1 0 0 1 0 0 1 1 1]
 [1 0 1 0 1 0 1 1 1 0 1 1 1 0 0]
 [1 1 0 0 1 1 0 1 0 1 1 1 1 0 0]
 [0 1 1 0 1 1 1 0 0 1 1 1 1 0 1]
 [1 0 1 0 0 0 0 0 0 0 1 1 1 0 1]
 [0 1 0 1 1 1 0 0 0 1 0 0 0 0 1]
 [1 1 1 0 0 0 0 0 1 1 1 0 0 1 1]
 [1 0 0 1 0 1 0 0 1 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 0 1 0 1 1 0 1 0]
 [1 0 0 1 1 1 0 0 0 1 1 0 0 0 0]
 [0 1 0 0 0 1 1 1 0 0 1 0 1 0 1]
 [1 1 0 0 0 0 1 1 1 1 0 0 0 0 1]]


In [4]:
#Se penalizan los padres que no cumplen P > 10 y se vuelven a generar aleatorios
p = np.zeros(15,dtype=int)

for i in range (15):
  p[i] = 0
  for j in range (15):
    p[i] = p[i] + matriz[i][j]

  print (p[i],i)

  if p[i] > 10:
    p[i] = 0
    for c in range(15):
      matriz[i][c] = randint(0, 1)
      p[i] = p[i] + matriz[i][c]
    print (p[i],i)
    i = i - 1

print(matriz)
print(p)

5 0
7 1
12 2
5 2
6 3
9 4
9 5
10 6
6 7
6 8
8 9
6 10
6 11
6 12
7 13
7 14
[[1 0 0 0 0 0 1 1 0 0 1 0 1 0 0]
 [0 0 1 0 0 1 0 1 1 1 0 0 1 0 1]
 [1 0 1 0 0 0 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 1 0 1 0 0 1 0 0 1 1 1]
 [1 0 1 0 1 0 1 1 1 0 1 1 1 0 0]
 [1 1 0 0 1 1 0 1 0 1 1 1 1 0 0]
 [0 1 1 0 1 1 1 0 0 1 1 1 1 0 1]
 [1 0 1 0 0 0 0 0 0 0 1 1 1 0 1]
 [0 1 0 1 1 1 0 0 0 1 0 0 0 0 1]
 [1 1 1 0 0 0 0 0 1 1 1 0 0 1 1]
 [1 0 0 1 0 1 0 0 1 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 0 1 0 1 1 0 1 0]
 [1 0 0 1 1 1 0 0 0 1 1 0 0 0 0]
 [0 1 0 0 0 1 1 1 0 0 1 0 1 0 1]
 [1 1 0 0 0 0 1 1 1 1 0 0 0 0 1]]
[ 5  7  5  6  9  9 10  6  6  8  6  6  6  7  7]


In [5]:
#Se generan los coeficientes de la funcion objetivo aleatoriamente
coef = []

for x in range(15):
    coef.append(randint( 1, 5))

coef = np.array(coef)

print (coef)

[5 5 3 4 1 2 4 2 3 5 4 2 3 2 4]


In [6]:
#Se calcula la funcion objetivo de cada cromosoma y las probabilidades
z = np.zeros(15,dtype=int)
prob = np.zeros(15)
probAcum = np.zeros(15)

zTotal = 0

for k in range(15):
  z[k] = coef[0]*matriz[k][0] + coef[1]*matriz[k][1] + coef[2]*matriz[k][2] + coef[3]*matriz[k][3] + coef[4]*matriz[k][4] + coef[5]*matriz[k][5] + coef[6]*matriz[k][6] + coef[7]*matriz[k][7] + coef[8]*matriz[k][8] + coef[9]*matriz[k][9] + coef[10]*matriz[k][10] + coef[11]*matriz[k][11] + coef[12]*matriz[k][12] + coef[13]*matriz[k][13] + coef[14]*matriz[k][14]
  zTotal = zTotal + z[k]

prob = z/zTotal

for y in range(15):
  probAcum[y] = probAcum[y-1] + prob[y]

print(z) 
print(prob)
print(probAcum)

[18 22 16 19 27 29 33 21 21 31 21 21 21 24 28]
[0.05113636 0.0625     0.04545455 0.05397727 0.07670455 0.08238636
 0.09375    0.05965909 0.05965909 0.08806818 0.05965909 0.05965909
 0.05965909 0.06818182 0.07954545]
[0.05113636 0.11363636 0.15909091 0.21306818 0.28977273 0.37215909
 0.46590909 0.52556818 0.58522727 0.67329545 0.73295455 0.79261364
 0.85227273 0.92045455 1.        ]


In [7]:
#Se seleccionan dos individuos de la poblacion
pCru = 0.9
pMut = 0.1
ind = 1/15
hijoTemp01 = np.zeros(15)
hijoTemp02 = np.zeros(15)

rand_ind01 = uniform(0, 1)
rand_ind02 = uniform(0, 1)

for m in range(15):
  if rand_ind01 < ((m + 1) * ind):
    print(rand_ind01, " < ", ((m + 1) * ind))
    hijoTemp01 = matriz[m][:]
    break
  

for n in range(15):
  if rand_ind02 < ((n + 1) * ind):
    print(rand_ind02, " < ", ((n + 1) * ind))
    hijoTemp02 = matriz[n][:]
    break

print(hijoTemp01)
print(hijoTemp02)

0.8632281491510775  <  0.8666666666666667
0.9374606334873633  <  1.0
[1 0 0 1 1 1 0 0 0 1 1 0 0 0 0]
[1 1 0 0 0 0 1 1 1 1 0 0 0 0 1]


In [10]:
#Se realiza el cruze de los hijos temporales
pCor = uniform(0, 1)
hijoCruz01 = np.zeros(15)
hijoCruz02 = np.zeros(15)

if uniform(0, 1) < pCru:
  print ("Cruzar!")
  for p in range(15):
    if pCor < ((p + 1) * ind):
      print(pCor, " < ", ((p + 1) * ind), "p = ", p)
      hijoTemp01_1 = np.zeros(p)
      hijoTemp01_2 = np.zeros(p)
      hijoTemp02_1 = np.zeros(p)
      hijoTemp02_2 = np.zeros(p)

      hijoTemp01_1 = hijoTemp01[:p]
      hijoTemp01_2 = hijoTemp01[p:]
      hijoTemp02_1 = hijoTemp02[:p]
      hijoTemp02_2 = hijoTemp02[p:]

      hijoCruz01 = np.concatenate((hijoTemp01_1, hijoTemp02_2))
      hijoCruz02 = np.concatenate((hijoTemp02_1, hijoTemp01_2))

      print(hijoTemp01, hijoTemp01_1, hijoTemp01_2)
      print(hijoTemp02, hijoTemp02_1, hijoTemp02_2)
      print(hijoCruz01, hijoCruz02)
      break

Cruzar!
0.9869784692009221  <  1.0 p =  14
[1 0 0 1 1 1 0 0 0 1 1 0 0 0 0] [1 0 0 1 1 1 0 0 0 1 1 0 0 0] [0]
[1 1 0 0 0 0 1 1 1 1 0 0 0 0 1] [1 1 0 0 0 0 1 1 1 1 0 0 0 0] [1]
[1 0 0 1 1 1 0 0 0 1 1 0 0 0 1] [1 1 0 0 0 0 1 1 1 1 0 0 0 0 0]


In [11]:
#Se realiza la mutacion de los hijos temporales
mutacion = []

for r_m in range(2):
    fila_m = []

    for c_m in range(15):
        fila_m.append(uniform(0, 1))
    
    mutacion.append(fila_m)

mutacion = np.array(mutacion)

print(mutacion)
print(hijoCruz01, hijoCruz02)

for q_0 in range(15):
  if mutacion[0][q_0] < pMut:
    print(mutacion[0][q_0], " < ", pMut, " q_0 = ", q_0)
    if hijoCruz01[q_0] == 1:
      hijoCruz01[q_0] = 0
    else:
      hijoCruz01[q_0] = 1

for q_1 in range(15):
  if mutacion[1][q_1] < pMut:
    if hijoCruz02[q_1] == 1:
      print(mutacion[1][q_1], " < ", pMut, " q_1 = ", q_1)
      hijoCruz02[q_1] = 0
    else:
      hijoCruz01[q_1] = 1

print(hijoCruz01, hijoCruz02)

[[9.34090442e-01 3.39757070e-01 4.44609287e-01 6.66928194e-01
  9.37520488e-01 9.24160103e-01 6.21017303e-01 4.14707407e-01
  9.20665317e-02 2.75291541e-01 2.81116864e-01 2.23462791e-02
  6.27693988e-02 6.40704445e-01 7.75775815e-01]
 [2.27498146e-01 3.25992914e-04 9.71011038e-01 3.73181507e-01
  2.73918351e-02 1.21957811e-01 8.46068423e-01 4.08260951e-01
  5.20296854e-01 8.48609118e-01 1.38100321e-01 1.30079987e-01
  8.61237503e-01 1.79457351e-01 2.34157090e-01]]
[1 0 0 1 1 1 0 0 0 1 1 0 0 0 1] [1 1 0 0 0 0 1 1 1 1 0 0 0 0 0]
0.09206653166868017  <  0.1  q_0 =  8
0.022346279124017654  <  0.1  q_0 =  11
0.06276939882159349  <  0.1  q_0 =  12
0.00032599291406654185  <  0.1  q_1 =  1
[1 0 0 1 1 1 0 0 1 1 1 1 1 0 1] [1 0 0 0 0 0 1 1 1 1 0 0 0 0 0]


In [13]:
#Se verifican los hijos que realmente cumplen con la restriccion P < 10
p_Hijos = np.zeros(2, dtype=int)

hijoCruz01 = np.array(hijoCruz01).reshape(1, -1)
hijoCruz02 = np.array(hijoCruz02).reshape(1, -1)

hijosCruz = np.concatenate((hijoCruz01, hijoCruz02))
print(hijosCruz)

for i in range (2):
  p_Hijos[i] = 0
  for j in range (15):
    p_Hijos[i] = p_Hijos[i] + hijosCruz[i][j]

  if p_Hijos[i] <= 10:
    print(i+1)
    
print(p_Hijos)

[[1 0 0 1 1 1 0 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 1 1 1 1 0 0 0 0 0]]
1
2
[10  5]
